### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by ronperris** [ronperris/zoom#5]
# Motivation
We want to be able to start the movement of the cars.

# Tasks
- [x] Create instructions for starting the car.
- [x] Create a method that starts the car.
- [x] Create an event listener that starts the car in motion.

![image](https://user-images.githubusercontent.com/963451/27756140-ea0ed316-5da9-11e7-8b47-8fcb1878be59.png)

**Comment by ronperris** [comment]
![image](https://user-images.githubusercontent.com/963451/27756463-726a2ca4-5dac-11e7-8ac4-06ee542bc462.png)
