### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by ronperris** [ronperris/zoom#7]
# Motivation
Users want to be able to stop their car.

# Tasks
- [x] Add instructions for stopping a car with `s`.
- [x] Add a static method for stopping a particular car.
- [x] Add an event listener for `s` to stop a particular car.

# Mockup
![image](https://user-images.githubusercontent.com/963451/27756506-01c53b78-5dad-11e7-92ab-dd543aa5ff62.png)

**Comment by ronperris** [comment]
![image](https://user-images.githubusercontent.com/963451/27756791-b77f9ca4-5daf-11e7-8bfb-abf70ab664ed.png)
